### ISSUE TITLE
Futures support

### ISSUE THREAD

**Issue by andreimerfu** [rodrigo-brito/ninjabot#106]
Do you have any plan to add support for Binance futures in the near future? Thanks!

**Comment by rodrigo-brito** [comment]
Hi @andreimerfu, I am planning to support Binance Futures. But this will take a while. I'm working alone on the project.

**Comment by andreimerfu** [comment]
Let me know how I can help with this feature. I'm not sure how do you want to include this feature in the current codebase. I'm wondering how we can change the Balance struct by using terms like `Wallet Balance`, `Margin Balance`, and `Unrealized PNL` without damaging the SPOT market. Also, I'm not sure where we'll introduce the leverage details for each asset.

Any feedback, ideas from your side will be helpful. Thanks! 🙇🏻

**Comment by rodrigo-brito** [comment]
@andreimerfu we can create a new branch to explore some ideias, what you think?

**Comment by rodrigo-brito** [comment]
Currently, this is the structure of the bot
![image](https://user-images.githubusercontent.com/7620947/160725608-feb5303a-871c-40e0-a127-b5fe336a4709.png)

We can use all the structure of Data Feeds, Order Feeds, Plugins and Storage.

We have to modify controllers and exchange modules. The exchange is an interface composed by two parts
- Broker - Execute operations (buy, sell, stop, etc)
- Feeder - Deal with data, candles, etc.

When we are in a backtesting, we use `Broker = Paperwallet`, `Feeder = CSV Feeder`
When we are in a simulation with live data, we use `Broker = Paperwallet`, `Feeder  = Binance`
When we are in production environment, we user `Broker = Binance`, `Feeder = Binance`

Theses abstractions helps to create different scenarios.

All the orders and candles are transmitted with pub-sub pattern in "feeds". For exemple, the chart moduele receives `candles` and `orders`, then it requires a subscription in `OrderFeed` and `DataFeed`.

The concept is simple, but we have a big issue with the leverage token and isolation of wallets.

**Comment by rodrigo-brito** [comment]
Now we have a testnet for futeres, it will be great in the module implementation: https://testnet.binancefuture.com/en/futures/BTCUSDT

**Comment by rodrigo-brito** [comment]
Initial support available
```
binance, err := exchange.NewBinanceFuture(ctx,
	exchange.WithBinanceFutureCredentials(cfg.BinanceKey, cfg.BinanceSecret),
)
``
