### ISSUE TITLE
reckon could remove Preload function for warming?

### ISSUE THREAD

**Issue by davidxiao** [rodrigo-brito/ninjabot#119]
Hello, @rodrigo-brito, mate,
   Thanks for your great work for the project.
   I could not wait to play with it today, it's wonderful. 
   But a question about if function `Proload` is a valid usage here?
   https://github.com/rodrigo-brito/ninjabot/blob/main/ninjabot.go#L298
   `Proload` is used to set up consuming candle, but its subscription is empty yet( subscribed from line 315), so at this stage, it will not do anything?

Thanks

**Comment by rodrigo-brito** [comment]
You can setup the "Warmup Period" in your strategy, just put zero, and it will not preload candles.
