### ISSUE TITLE
Improve `/balance` command performance

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#123]
When we request the balance summary, ninjabot will request the position for each trading pair and report a summary.
But in this case, we request the same function multiple times: `binance.Account()`

https://github.com/rodrigo-brito/ninjabot/blob/1a3585bedbaf66ba35e9377635877aa688e5a1e0/exchange/binance.go#L444-L455

A good approach to improve the performance are: Request `binance.Account()` once and calculate the summary for all pairs in the same time.

**Comment by panapol-p** [comment]
I would like to do this feature ;)

**Comment by panapol-p** [comment]
I find better solution for this issue, I will work on it first, the pull request was cloesd that need implement 2 function with the same functional for new exchange it is not good I think

**Comment by rodrigo-brito** [comment]
Ok @panapol-p, thank you for the help!

**Comment by panapol-p** [comment]
Hi @rodrigo-brito  after I try to work with my new idea, it's not worked
now I re-open the pull request.
could you please review this one thank you.

**Comment by rodrigo-brito** [comment]
Hi @panapol-p, thank you. I will check soon.

**Comment by panapol-p** [comment]
Hi, @rodrigo-brito  I think this issue was fixed. may be we can close this issue. or you have any suggestion for this one?

**Comment by rodrigo-brito** [comment]
Sure! Closing due #184
