### ISSUE TITLE
should it be `>=`?

### ISSUE THREAD

**Issue by davidxiao** [rodrigo-brito/ninjabot#132]
this line 
https://github.com/rodrigo-brito/ninjabot/blob/main/exchange/paperwallet.go#L250

it seems a bug?
when the order is buy, should buy only when `order.Price >= candle.Close`?

**Comment by rodrigo-brito** [comment]
No, it is like an Order Limit, if your "Limit Price" is bellow the market value, your order is executed.
We have unit tests for this, you can check here: https://github.com/rodrigo-brito/ninjabot/blob/main/exchange/paperwallet_test.go#L19-L33

**Comment by davidxiao** [comment]
hi, @rodrigo-brito , mate,
   Sorry, doesn't makes sense to me yet, 
   Yes, it's limited order, let's say i place a buy order for BTC with price $10000, and currently the candle.price is : $46000, according to the logic, the order will execute?

Thanks

**Comment by rodrigo-brito** [comment]
Exact! Market orders and limit orders, both will execute!

**Comment by davidxiao** [comment]
but I can not buy BTC with $1000 whose current price is $46000, right?

**Comment by rodrigo-brito** [comment]
@davidxiao I created a Discord server, for general chat: https://discord.gg/TGCrUH972E

**Comment by rodrigo-brito** [comment]
Now I got my mistake, it is a bug.  tried some simulations here and understand  the problem. I was confusing the order with SideSell but it's SideBuy
