### ISSUE TITLE
Display max drawdown in a trade

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#18]
Drawdown is a good indicator for trade entries.
Will be great if Ninjabot display the max drawdown reported in backtesting.

Reference https://en.wikipedia.org/wiki/Drawdown_(economics)

**Comment by FreddyJilson** [comment]
Hi, I am interested to take a look at this. Could you please assign the task to me?

**Comment by FreddyJilson** [comment]
Hi, I am interested to take a look. Could you please assign the task to me?

**Comment by rodrigo-brito** [comment]
Hi @FreddyJilson, shure!

**Comment by FreddyJilson** [comment]
thanks!

**Comment by rodrigo-brito** [comment]
No problem @FreddyJilson
