### ISSUE TITLE
Wrong param parsing for CLI 

### ISSUE THREAD

**Issue by atanasbozhkov** [rodrigo-brito/ninjabot#2]
I tried to use the ninjabot CLI (both Linux x64_86 version and Windows version) to download historical data. Same thing happens on v.0.0.1 and 0.0.2

If I use it as per the documentation 
` ./ninjabot download --pair ETHUSDT --timeframe 1d --days 30 --output ./eth.csv`

I get the following resutl: 
```
NAME:
   download - download historical data

USAGE:
   ninjabot [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --pair value, -p value       eg. BTCUSDT
   --days value, -d value       eg. 100 (default 30 days) (default: 0)
   --start value, -s value      eg. 2021-12-01 (default: (*time.Time)(nil))
   --end value, -e value        eg. 2020-12-31 (default: (*time.Time)(nil))
   --timeframe value, -t value  eg. 1h
   --output value, -o value     eg. ./btc.csv
   --help, -h                   show help (default: false)
2021/05/21 11:05:45 Required flags "pair, timeframe, output" not set
```

However passing the params before the `download` command - seems to work 
```
 ./ninjabot --pair ETHUSDT --timeframe 1d --days 30 --output ./eth.csv download
INFO[0000] [SETUP] Using Binance exchange
INFO[0000] Downloading 30 candles of 1d for ETHUSDT
INFO[0000] Done!
```

Seems like either the documentation or the params parsing is wrong - let me know what the correct behaviour is and I can take a look and raise a PR.

**Comment by rodrigo-brito** [comment]
You are right, the command `download` is useless, the fix is very simple.
We need to move the `Action` code to a subcommand https://github.com/urfave/cli/blob/master/docs/v2/manual.md#subcommands:

```go
    Commands: []*cli.Command{
      {
        Name:    "download",
        Action:  func(c *cli.Context) error {
          ....
        },
      },
   }
```

Currently, the code is in the root of CLI.

**Comment by rodrigo-brito** [comment]
Closed by https://github.com/rodrigo-brito/ninjabot/commit/6234e1910b6ddeb869e8a97d48a5863cf4c92ce9
