### ISSUE TITLE
Create a template for issues and pull requests

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#20]
We need a template for issues and pull requests

How Github template works: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

Examples of issues templates: https://github.com/search?utf8=%E2%9C%93&q=in%3Apath+issue_template.md&type=Code&ref=searchresults

Examples of PR templates: https://github.com/search?utf8=%E2%9C%93&q=in%3Apath+pull_request_template.md&type=Code&ref=searchresults

**Comment by Shatakshi0805** [comment]
Hi, I would like to work on this. Could you please assign this issue to me?

**Comment by rodrigo-brito** [comment]
Hi @Shatakshi0805, shure! Feel free to choose a template.

**Comment by rodrigo-brito** [comment]
We have a openning PR for Pull Request templates (https://github.com/rodrigo-brito/ninjabot/pull/22)
Can you help me with the issue template?

**Comment by Shatakshi0805** [comment]
yes, definitely. would be making a PR soon.

**Comment by Shatakshi0805** [comment]
I have made the PR. Please review the same.

**Comment by rodrigo-brito** [comment]
Closed by https://github.com/rodrigo-brito/ninjabot/pull/23
