### ISSUE TITLE
Remove usage of Ent framework

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#21]
We use Ent framework in a few operations when we need to register a new order or calculate the average profit. But we can replace with direct queries in SQLite.

Database schema: https://github.com/rodrigo-brito/ninjabot/blob/main/storage/schema/order.go

- [ ] Remove the code from https://github.com/rodrigo-brito/ninjabot/blob/main/storage
- [ ] Create a repository and operations for
  - [ ] Create and update orders
  - [ ] Select pending orders
  - [ ]  Calculate average price

Libray usages
- https://github.com/rodrigo-brito/ninjabot/blob/main/order/controller.go#L121-L125
- https://github.com/rodrigo-brito/ninjabot/blob/main/order/controller.go#L202-L209
- https://github.com/rodrigo-brito/ninjabot/blob/main/order/controller.go#L287-L299

**Comment by rafaelrubbioli** [comment]
I would like to help with this one!

**Comment by rafaelrubbioli** [comment]
I opened [a pr](https://github.com/rodrigo-brito/ninjabot/pull/29) for this issue!
