### ISSUE TITLE
Remove header `trades`

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#212]
The header `trades` is not required.
The function `ToSlice()` is not inserting value for this column: https://github.com/rodrigo-brito/ninjabot/blob/0dcd4382a40d5255be8c73c30633e06b2694f900/model/model.go#L85-L93

You have to remove the header here and fix the tests (if needed)
https://github.com/rodrigo-brito/ninjabot/blob/main/download/download.go#L100

**Comment by rafaelrubbioli** [comment]
@rodrigo-brito can i work on this one?

**Comment by rafaelrubbioli** [comment]
I opened a [PR](https://github.com/rodrigo-brito/ninjabot/pull/213) for this!
