### ISSUE TITLE
Include unit tests for download module

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#27]
We need to improve the coverage of Download module: https://github.com/rodrigo-brito/ninjabot/blob/main/download/download.go

You can use the CSV Feed as data source to simulate the exchange.

```go
csvFeed, err := exchange.NewCSVFeed(
		 "1h",
		exchange.PairFeed{
			Pair:      "BTCUSDT",
			File:      "testdata/btc-1h.csv",
			Timeframe: "1h",
		},
}
```

**Comment by LucasZatta** [comment]
Hi there! Could you please assign me this issue ? :)

**Comment by rodrigo-brito** [comment]
Hi @LucasZatta, have fun!

**Comment by LucasZatta** [comment]
Thanks @rodrigo-brito !
