### ISSUE TITLE
Create MACD indicator for Ninjabot Chart

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#33]
To implement MACD, we need to implement a new Struct similar to EMA: https://github.com/rodrigo-brito/ninjabot/blob/516e75064107daf73495bf1d091b5dc1cba18c09/plot/indicator/ema.go

The struct must implement the following interface:
```go
type Indicator interface {
	Name() string
	Overlay() bool
	Metrics() []IndicatorMetric
	Load(dataframe *model.Dataframe)
}
``` 

MACD Indicator contains 3 metrics (value, signal, and histogram)
You can use TALIB to get these values: `talib.Macd(...)`

To test the new indicator, you can include it here:
https://github.com/rodrigo-brito/ninjabot/blob/516e75064107daf73495bf1d091b5dc1cba18c09/examples/backtesting/main.go#L58-L63

And run: `go run examples/backtesting/main.go`

**Comment by rodrigo-brito** [comment]
Hi @marco-silveira, how it is going? Do you need help with this issue?

**Comment by gunebakan** [comment]
Hi Rodrigo. I wrote the MACD indicator and plot it. How can I push it?

**Comment by rodrigo-brito** [comment]
Hi @gunebakan, shure.
