### ISSUE TITLE
Incorrect slice usage in Summary method

### ISSUE THREAD

**Issue by ramilexe** [rodrigo-brito/ninjabot#332]
In the `bot.Summary()` method, you allocate slice for `returnsPercent` with fixed length https://github.com/rodrigo-brito/ninjabot/blob/2325ed95bb6f0bac3d011443c4596b4329e9a695/ninjabot.go#L243 

Then you use `append` method to add elements to the slice and it increases size of the slice and, probably, calculate histogram incorrectly: https://github.com/rodrigo-brito/ninjabot/blob/2325ed95bb6f0bac3d011443c4596b4329e9a695/ninjabot.go#L245

**Comment by ramilexe** [comment]
Before fix:
![image](https://github.com/rodrigo-brito/ninjabot/assets/1008882/3380d829-10ab-4376-9857-36fe7337940c)

After fix:

![image](https://github.com/rodrigo-brito/ninjabot/assets/1008882/1c0d917d-9f4c-49aa-b2e7-b78c4c9dd9f9)

**Comment by rodrigo-brito** [comment]
You are right, this is a big mistake!
Thank you for the report and pull request

**Comment by rodrigo-brito** [comment]
Closed by https://github.com/rodrigo-brito/ninjabot/pull/333
