### ISSUE TITLE
PaperWallet.Cancel method doesn't reduce locked assets

### ISSUE THREAD

**Issue by ramilexe** [rodrigo-brito/ninjabot#338]
Test case:
* Create buy limit order
* Funds is being locked
* Cancel limit order
* Funds is still locked, that is incorrect

**Comment by ramilexe** [comment]
Hi @rodrigo-brito 
please reach out to me at telegram [@ramilexe](https://t.me/ramilexe). I have a few ideas regarding enhancement of ninjabot I would like to discuss with you

**Comment by rodrigo-brito** [comment]
Hi @ramilexe, thank you for the report. We can talk in Discord about improvements
