### ISSUE TITLE
Implement Bollinger Bands in Ninjabot Chart

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#34]
To implement Bolinger Bands, we need to implement a new Struct similar to EMA: https://github.com/rodrigo-brito/ninjabot/blob/516e75064107daf73495bf1d091b5dc1cba18c09/plot/indicator/ema.go

The struct must implement the following interface:
```go
type Indicator interface {
	Name() string
	Overlay() bool
	Metrics() []IndicatorMetric
	Load(dataframe *model.Dataframe)
}
``` 

BB Indicator contains 3 metrics (upper band, mid-band, and lower band)
You can use TALIB to get these values: `talib.BBands(...)`

To test the new indicator, you can include it here:
https://github.com/rodrigo-brito/ninjabot/blob/516e75064107daf73495bf1d091b5dc1cba18c09/examples/backtesting/main.go#L58-L63

And run: `go run examples/backtesting/main.go`

**Comment by vinicio** [comment]
Hi, sir, can I please have the pleasure to implement that?

**Comment by rodrigo-brito** [comment]
> Hi, sir, can I please have the pleasure to implement that?

Shure!

![image](https://user-images.githubusercontent.com/7620947/135860088-0e563ff1-adb7-4399-98e4-fd00a37c8c18.png)
