### ISSUE TITLE
Configuration Issues (Newbie)

### ISSUE THREAD

**Issue by opserc20** [rodrigo-brito/ninjabot#351]
Hello guys,

i am trying to set the bot to work and i can't!

Can somebody give some help to make it work, i want to make it work with real trading, not for test.

**Comment by opserc20** [comment]
@rodrigo-brito da uma ajuda aí 🙂✌️

**Comment by rodrigo-brito** [comment]
You can check out a getting started here: https://rodrigo-brito.github.io/ninjabot/docs/getting-started/
