### ISSUE TITLE
small websocket reliabilty improvements.

### ISSUE THREAD

**Issue by spreeker** [rodrigo-brito/ninjabot#40]
https://github.com/rodrigo-brito/ninjabot/blob/67e91b0ba93f7aabbb18f048e85c039e03c1d50e/exchange/binance.go#L470

setting this to true helps.

`binance.WebsocketKeepalive = true`

func StartListenIn(ccandle chan Candle, cerr chan error, symbol Symbol, period string) error {

	done, _, err := binance.WsKlineServe(string(symbol), period, func(event *binance.WsKlineEvent) {
		ccandle <- CandleFromWsKline(symbol, event.Kline)
	}, func(err error) {
		cerr <- err
	})

	if err != nil {
		<-done
		return err
	}
	return nil
}

Im using this now:

```
func StartListenIn(ccandle chan Candle, cerr chan error, symbol Symbol, period string) error {

	done, _, err := binance.WsKlineServe(string(symbol), period, func(event *binance.WsKlineEvent) {
		ccandle <- CandleFromWsKline(symbol, event.Kline)
	}, func(err error) {
		cerr <- err
	})

	if err != nil {
		<-done
		return err
	}
	return nil
}


func (b *Binance) CandlesSubscription(symbol Symbol, period string) (chan Candle, chan error) {
	ccandle := make(chan Candle)
	cerr := make(chan error)

	binance.WebsocketKeepalive = true

	go func() {
		errors := 0
		for {
			err := StartListenIn(ccandle, cerr, symbol, period)

			if err != nil {
				cerr <- err
				log.Error(err)
				errors++
			}

			//lets continue..

			if errors > 10 {
				break
				panic(err)
			}
		}

		close(cerr)
		close(ccandle)
		return
	}()

	return ccandle, cerr
}
```

**Comment by rodrigo-brito** [comment]
I'm using a different strategy.
The infinite loop with the `for` is necessary to key the connection opened for a long time, Binance guarantees only 24h of open connection and closes this without an error.

This format stop with a single condition: Context cancelation.
I the example posted bellow, you connection will close in 24h (sometimes more)

We also uses the keep alive parameter here:
https://github.com/rodrigo-brito/ninjabot/blob/main/exchange/binance.go#L57

But is used only to keep the `ping-pong` Binance check.

**Comment by spreeker** [comment]
Hi but the context cancellation test is only called when the web-socket connection return without error. once a day. 
So bot solutions work just fine since they are in an infinite loop.
If the connection fails you might want to hard crash the program since you dont want to "think" or pretend you are running.

**Comment by spreeker** [comment]
Ah I looked at the source and `done` is a channel. So the select at the end of the for loop is 'blocking' on either context of connection done :) . I thought the WsKlineService was blocking.
