### ISSUE TITLE
Include button to export CSV with orders in chart page

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#53]
We can include a new API endpoint, eg. `https://localhost:8080/trades.csv` which returns all trades performed in a given backtesting.
Then, we can include a button in the chart page to access this endpoint and download all trades performed.

**Comment by panapol-p** [comment]
I would like to do this feature.

**Comment by rodrigo-brito** [comment]
Have fun @panapol-p!

**Comment by rodrigo-brito** [comment]
Closed by https://github.com/rodrigo-brito/ninjabot/pull/86
