### ISSUE TITLE
Balanced portfolio settings

### ISSUE THREAD

**Issue by seguidor777** [rodrigo-brito/ninjabot#64]
Hi all,

I'm writing a ninjabot client and I want to handle a balanced portfolio as in this project [1]. I saw that we can pass a pairs list to the ninjabot settings, but we cannot specify the weight for each asset. Are you interested on implementing this feature? if so, I could help with the implementation, I have good experience in Go. If not, I'll have to work in a separate fork to make use of this feature.

Thanks,
Jorge

[1] https://github.com/kdmukai/binance_bbb#customize-your-portfolio

**Comment by rodrigo-brito** [comment]
Hi @seguidor777, the Ninjabot allows the developer to control the size of each order. Then you can set the weight in your strategy and create orders to balance the position in a period of time. I will create an example for you. Just a minute.
