### ISSUE TITLE
csv float precision default %f is not good enough for many assets. BIG FAT BUG!!

### ISSUE THREAD

**Issue by spreeker** [rodrigo-brito/ninjabot#72]
func (c Candle) ToSlice() []string

uses %f to describe floats. close, open high and low prices.

which in the case of shiba inu  and others gives candles like these missing some data...

1632200100**,0.000007,0.000007,0.000007,0.000007,**6735653639.0,62
1632200400,0.000007,0.000007,0.000007,0.000007,6397726216.0,115
1632200700,0.000007,0.000007,0.000007,0.000007,14491282312.0,71

It ofcourse should contain: 0.00000798374 a lot more precision.
either use %.10f or  default precision leading to large csv files of use symbol info provided binance.

My backtester had unreasonable good results for shiba. Now I know why....

**Comment by rodrigo-brito** [comment]
Hi @spreeker, thank you for the report.
Indeed, this precision may affect the results.
A good way do improve this precision is using pair precision given by Binance here: https://api.binance.com/api/v1/exchangeInfo

![image](https://user-images.githubusercontent.com/7620947/143660544-73b8597e-5414-49ad-bed2-99fa1d6ccd78.png)

As we can see, DOGE has 8 digits of precision, and we can use a custom precision for each coin fetch.

**Comment by rodrigo-brito** [comment]
Closed by https://github.com/rodrigo-brito/ninjabot/commit/6c0593e779939f1c889f666f510b7c249c322604

**Comment by rodrigo-brito** [comment]
@spreeker I will create a new release with the fix. Please, can you update your CLI and try to download the dataset again?
