### ISSUE TITLE
Include progressbar in dowloading

### ISSUE THREAD

**Issue by panapol-p** [rodrigo-brito/ninjabot#76]
## Description
sometime when I downlaod big data I didnt know it is working or not (no result more than 10 min)

## Relevant Context
add progress bar to show progress by revise func Download in download.go

## Steps to Solution(s)
revise download.go and try to download big historical data

## Links to Resources
progress bar [https://github.com/schollz/progressbar](https://github.com/schollz/progressbar)

**Comment by panapol-p** [comment]
hi @rodrigo-brito, I found lost candle data during work this feature

when load candle more than 500 , it will be split by batchSize for 500 each loop
some range of time, binance is not return full of 500 (may be gap or lose stamp data or etc)

for example
[https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=5m&startTime=1628698800000&endTime=1628848800000](https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=5m&startTime=1628698800000&endTime=1628848800000)

candleCount -> 500 but actual data is 447
we should print how many lose data or not? I think it will impact to quality of data if data is not smooth

**Comment by rodrigo-brito** [comment]
It looks like a big problem. I think we have two options:
- First, we can only display a warning informing the missing data interval.
- Second, we can interpolate the result for missing data and fill this interval.

What you think about it?

**Comment by panapol-p** [comment]
I think infrom by waning meessage is better because after i try to pulled data by using below
download --pair BTCUSDT --timeframe 1h --days 120

I found lost data more than 4 rows (4 hours)
![image](https://user-images.githubusercontent.com/34530268/144448514-3306d55c-33f4-4531-8edc-cf34ba4d8830.png)

and 2 rows (2 hours)
![image](https://user-images.githubusercontent.com/34530268/144449029-337eed7a-1922-4793-9f56-13c2546bb888.png)

if lost only one row each time i think we can fill it but sometime lost many rows, warning message is better
__________________________________________________________________________________________
And I found Duplicate Data from CSV (I will fix this one too)
![image](https://user-images.githubusercontent.com/34530268/144451015-728d3852-f13e-48ff-9cab-b2fdf44ecfb8.png)

**Comment by rodrigo-brito** [comment]
Great! Normally i use smaller timeframe for candlesticks and convert to a larger timeframe, so I don't even notice these problems.

**Comment by rodrigo-brito** [comment]
Closed by #79
