### ISSUE TITLE
Is there any document about the project ?

### ISSUE THREAD

**Issue by wade-liwei** [rodrigo-brito/ninjabot#85]
hello there 

Do you have document for introduce the project,
I am a blockchain engineer.

**Comment by wade-liwei** [comment]
do you have real time chat group ?

**Comment by rodrigo-brito** [comment]
Hi @wade-liwei, we have a small getting started here: https://rodrigo-brito.github.io/ninjabot/docs/getting-started/
We do not have a chat group.

For discussions, we have https://github.com/rodrigo-brito/ninjabot/discussions
