### ISSUE TITLE
Improve Telegram error handling

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/ninjabot#88]
When the bot fail placing an order, the final message do not includes information about the order. For example:
![image](https://user-images.githubusercontent.com/7620947/147854067-cce4fd8b-9786-4a68-9a9a-1ba3b207f7ac.png)

In this case, we can include information about the trading pair, order size, and order type.

**Comment by RobertKwiatkowski** [comment]
I wanted to resolve this issue however the entire logic is a little bit complicated to me:
At this moment I created function:
```
func (c *Controller) notifyBuyError(pair string, amount float64, side model.SideType, err error) {
	errMessage := fmt.Errorf("Pair: %s, Amount: %v, Type: %s\n-----\n%s", pair, amount, side, err)
	log.Error(errMessage)
	if c.notifier != nil {
		c.notifier.OnError(errMessage)
	}
}
```
And used it inside `func (c *Controller) CreateOrderMarketQuote(side model.SideType, pair string, amount float64) (model.Order, error)`
However I'm not sure if it's the best/cleanest way.

**Comment by RobertKwiatkowski** [comment]
![Screenshot_20220320-003122_Telegram](https://user-images.githubusercontent.com/101144854/159141956-dea6478d-2f8e-4bee-bde7-c1b376f2f636.jpg)
