### ISSUE TITLE
No data processed whth $SHIB

### ISSUE THREAD

**Issue by SeriousM** [rodrigo-brito/ninjabot#9]
Hi, first of all, thank you for this project. I'm a professional c# architect and this project helps me a lot to  learn about trading bots and go.

I tried the backtesting with the SHIB coin (I know.. just see how many loss the bot would have taken) but for some reason the output shows NaNs and zeros, the chart is empty.

```
$ go run example/backtesting/main.go
INFO[2021-05-25 07:22] [SETUP] Using paper wallet                   
INFO[2021-05-25 07:22] [SETUP] Initial Portfolio = 6000.000000 USDT 
+-------+--------+-----+------+-------+--------+--------+
| PAIR  | TRADES | WIN | LOSS | % WIN | PAYOFF | PROFIT |
+-------+--------+-----+------+-------+--------+--------+
+-------+--------+-----+------+-------+--------+--------+
| TOTAL |      0 |   0 |    0 | NAN % |    NAN | 0.0000 |
+-------+--------+-----+------+-------+--------+--------+
--------------
WALLET SUMMARY
--------------
6000.000000 USDT
--------------
START PORTFOLIO =  6000 USDT
FINAL PORTFOLIO =  6000 USDT
GROSS PROFIT    =  0.000000 USDT (0.00%)
MARKET CHANGE   =  NaN%
```

What could be the problem? SHIB developed itself as starting very high but falling since the first pump/dump.
Maybe the bot didn't tried a single trade and therefore the report is empty?

Thank you!

**Comment by rodrigo-brito** [comment]
> Hi, first of all, thank you for this project. I'm a professional c# architect and this project helps me a lot to learn about trading bots and go.
I'm glad you enjoyed the project.

> SHIB developed itself as starting very high but falling since the first pump/dump.
If you are using the example strategy, it only buys in bull markets.
To debug your backtesting, you can enable logs changing the log level: `ninjabot.WithLogLevel(log.ErrorLevel)` in backtesting.

What is the time interval of the backtesting?

**Comment by SeriousM** [comment]
> What is the time interval of the backtesting?

the csv data was downloaded with 1h timeframe x 180 days.
`ninjabot.WithLogLevel(log.ErrorLevel)` is already set but when changed it just reports n-times 
```
...
INFO[2021-05-25 14:00] New Candle = SHIBUSDT2021-05-13 23:00:00 +0000 UTC 2.1e-05 
...
```

this is the shib-testdata.
[shibusdt.csv](https://github.com/rodrigo-brito/ninjabot/files/6539860/shibusdt.csv)

It's not a problem to me, I just wanted to check if the readout should be NaN instead "-3000% market change".

**Comment by rodrigo-brito** [comment]
The `NaN` is a bug. We divided the average of gains with the average of losses. This is the payoff formula. And division by zero results in an error.
