### ISSUE TITLE
code=-2014, API-key format invalid

### ISSUE THREAD

**Issue by bh90210** [rodrigo-brito/ninjabot#94]
Hello, 

I am getting this error 
```log
ERRO[2022-01-23 05:00] <APIError> code=-2014, msg=API-key format invalid. 
ERRO[2022-01-23 05:00] <APIError> code=-2014, msg=API-key format invalid. 
ERRO[2022-01-23 09:00] <APIError> code=-2014, msg=API-key format invalid. 
ERRO[2022-01-23 09:00] <APIError> code=-2014, msg=API-key format invalid. 
ERRO[2022-01-23 13:00] <APIError> code=-2014, msg=API-key format invalid. 
ERRO[2022-01-23 13:00] <APIError> code=-2014, msg=API-key format invalid.
```
I am assuming it is coming from somewhere in here? https://github.com/rodrigo-brito/ninjabot/blob/main/exchange/binance.go 

Any pointers as to why or how to solve this problem are welcome.

**Comment by rodrigo-brito** [comment]
Hi @bh90210, I think it is a problem with your Key from finance.  Have you checked the key content?

**Comment by bh90210** [comment]
I created a new one and still the same error. 
Prior to the error logging says everything works as expected. 

"Have you checked the key content?"
Can you please clarify what you mean by this?

**Comment by rodrigo-brito** [comment]
> Can you please clarify what you mean by this?

We define de API Key / API Secret when we create this block, correct?
https://github.com/rodrigo-brito/ninjabot/blob/main/examples/binance/main.go#L36-L40

Sometimes, the key comes from an ENV variable or a settings file, and a bug in this process may pass an empty variable, for example, a typo. My suggestion: print your key in the console with `fmt.Println` and check if is not empty.

**Comment by bh90210** [comment]
θη

**Comment by rodrigo-brito** [comment]
No problem.
